export const ADD_PACKAGE_REQUEST = "ADD_PACKAGE_REQUEST";
export const ADD_PACKAGE_SUCCESS = "ADD_PACKAGE_SUCCESS";
export const ADD_PACKAGE_FAILED = "ADD_PACKAGE_FAILED";

export const GET_PACKAGE_FAILED = "GET_PACKAGE_FAILED";
export const GET_PACKAGE_SUCCESS = "GET_PACKAGE_SUCCESS";
export const GET_PACKAGE_REQUEST = "GET_PACKAGE_REQUEST";

export const UPDATE_PACKAGE_REQUEST = "UPDATE_PACKAGE_REQUEST";
export const UPDATE_PACKAGE_SUCCESS = "UPDATE_PACKAGE_SUCCESS";
export const UPDATE_PACKAGE_FAILED = "UPDATE_PACKAGE_FAILED";

export const DELETE_PACKAGE_REQUEST = "DELETE_PACKAGE_REQUEST";
export const DELETE_PACKAGE_SUCCESS = "DELETE_PACKAGE_SUCCESS";
export const DELETE_PACKAGE_FAILED = "DELETE_PACKAGE_FAILED";

export const GET_SINGLE_PACKAGE_FAILED = "GET_SINGLE_PACKAGE_FAILED";
export const GET_SINGLE_PACKAGE_SUCCESS = "GET_SINGLE_PACKAGE_SUCCESS";
export const GET_SINGLE_PACKAGE_REQUEST = "GET_SINGLE_PACKAGE_REQUEST";
