export const ADD_TRIP_REQUEST = "ADD_TRIP_REQUEST";
export const ADD_TRIP_SUCCESS = "ADD_TRIP_SUCCESS";
export const ADD_TRIP_FAILED = "ADD_TRIP_FAILED";

export const UPDATE_TRIP_REQUEST = "UPDATE_TRIP_REQUEST";
export const UPDATE_TRIP_SUCCESS = "UPDATE_TRIP_SUCCESS";
export const UPDATE_TRIP_FAILED = "UPDATE_TRIP_FAILED";

export const DELETE_TRIP_REQUEST = "DELETE_TRIP_REQUEST";
export const DELETE_TRIP_SUCCESS = "DELETE_TRIP_SUCCESS";
export const DELETE_TRIP_FAILED = "DELETE_TRIP_FAILED";

export const GET_TRIP_REQUEST = "GET_TRIP_REQUEST";
export const GET_TRIP_SUCCESS = "GET_TRIP_SUCCESS";
export const GET_TRIP_FAILED = "GET_TRIP_FAILED";

export const GET_ALL_TYPE_REQUEST = "GET_ALL_TYPE_REQUEST";
export const GET_ALL_TYPE_SUCCESS = "GET_ALL_TYPE_SUCCESS";
export const GET_ALL_TYPE_FAILED = "GET_ALL_TYPE_FAILED";
