export const GET_BOOKING_FAILED = "GET_BOOKING_FAILED";
export const GET_BOOKING_SUCCESS = "GET_BOOKING_SUCCESS";
export const GET_BOOKING_REQUEST = "GET_BOOKING_REQUEST";

export const GET_BOOKING_BY_STATUS_FAILED = "GET_BOOKING_BY_STATUS_FAILED";
export const GET_BOOKING_BY_STATUS_SUCCESS = "GET_BOOKING_BY_STATUS_SUCCESS";
export const GET_BOOKING_BY_STATUS_REQUEST = "GET_BOOKING_BY_STATUS_REQUEST";

export const UPDATE_BOOKING_REQUEST = "UPDATE_BOOKING_REQUEST";
export const UPDATE_BOOKING_SUCCESS = "UPDATE_BOOKING_SUCCESS";
export const UPDATE_BOOKING_FAILED = "UPDATE_BOOKING_FAILED";

export const DELETE_BOOKING_REQUEST = "DELETE_BOOKING_REQUEST";
export const DELETE_BOOKING_SUCCESS = "DELETE_BOOKING_SUCCESS";
export const DELETE_BOOKING_FAILED = "DELETE_BOOKING_FAILED";

export const GET_SINGLE_BOOKING_FAILED = "GET_SINGLE_BOOKING_FAILED";
export const GET_SINGLE_BOOKING_SUCCESS = "GET_SINGLE_BOOKING_SUCCESS";
export const GET_SINGLE_BOOKING_REQUEST = "GET_SINGLE_BOOKING_REQUEST";

export const GET_NOTIFICATION_FAILED = "GET_NOTIFICATION_FAILED";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_REQUEST = "GET_NOTIFICATION_REQUEST";

export const UPDATE_BOOKING_STATUS_REQUEST = "UPDATE_BOOKING_STATUS_REQUEST";
export const UPDATE_BOOKING_STATUS_SUCCESS = "UPDATE_BOOKING_STATUS_SUCCESS";
export const UPDATE_BOOKING_STATUS_FAILED = "UPDATE_BOOKING_STATUS_FAILED";

export const ADD_BOOKING_NOTE_REQUEST = "ADD_BOOKING_NOTE_REQUEST";
export const ADD_BOOKING_NOTE_SUCCESS = "ADD_BOOKING_NOTE_SUCCESS";
export const ADD_BOOKING_NOTE_FAILED = "ADD_BOOKING_NOTE_FAILED";

export const GET_BOOKING_NOTE_REQUEST = "GET_BOOKING_NOTE_REQUEST";
export const GET_BOOKING_NOTE_SUCCESS = "GET_BOOKING_NOTE_SUCCESS";
export const GET_BOOKING_NOTE_FAILED = "GET_BOOKING_NOTE_FAILED";

export const UPDATE_BOOKING_NOTE_REQUEST = "UPDATE_BOOKING_NOTE_REQUEST";
export const UPDATE_BOOKING_NOTE_SUCCESS = "UPDATE_BOOKING_NOTE_SUCCESS";
export const UPDATE_BOOKING_NOTE_FAILED = "UPDATE_BOOKING_NOTE_FAILED";

export const DELETE_BOOKING_NOTE_REQUEST = "DELETE_BOOKING_NOTE_REQUEST";
export const DELETE_BOOKING_NOTE_SUCCESS = "DELETE_BOOKING_NOTE_SUCCESS";
export const DELETE_BOOKING_NOTE_FAILED = "DELETE_BOOKING_NOTE_FAILED";

